### ISSUE TITLE
Create Users Serializer

### ISSUE THREAD

**Issue by lcpulzone** [wdk3/knewharvest_be_api#11]
- [x] Create Users serializer (/app/serializers/api/v1/users_serializer.rb)
- [x] Add name, farm_name, address

**Comment by lcpulzone** [comment]
- [ ] Create Users serializer (/app/serializers/api/v1/users_serializer.rb)
- [ ] Add name, farm_name, address

**Comment by kon-ham** [comment]
The following PR seeks to resolve this issue: https://github.com/wdk3/knewharvest_be_api/pull/36
