### ISSUE TITLE
Create Sub_Location Serializer

### ISSUE THREAD

**Issue by lcpulzone** [wdk3/knewharvest_be_api#12]
Create Sub_Locations serializer (/app/serializers/api/v1/sub_locations_serializer.rb)
Add name, dimensions, micro_climate

**Comment by lcpulzone** [comment]
Create Sub-Locations serializer (/app/serializers/api/v1/sub_locations_serializer.rb)
 Add name, dimensions, micro_climate

**Comment by saltedseacorn** [comment]
Closing issue due to the fact this feature was included in the following PR: https://github.com/wdk3/knewharvest_be_api/pull/36
