### ISSUE TITLE
Create User Model

### ISSUE THREAD

**Issue by kon-ham** [wdk3/knewharvest_be_api#13]
- [x] Create User model (/app/model/user.rb)
- [x] Create test file for User model (/spec/models/user.rb)
- [x] Create tests for User model validations
- [ ] Ensure tests are passing

```
A User has a:
name
farm_name
address

And,

A user has many sub_locations
```

**Comment by kon-ham** [comment]
- [ ] Create User model (/app/model/user.rb)
- [ ] Create test file for User model (/spec/models/user.rb)

**Comment by kon-ham** [comment]
- [ ] Create tests for User model validations
- [ ] Ensure tests are passing

```
A User has a:
name
farm_name
address

And,

A user has many sublocations
```

**Comment by gaelyn** [comment]
I noticed that User does not currently have a `name`. Just `farm_name` and `address`. Should we add `name`?

**Comment by kon-ham** [comment]
I think sooner or later `name` will be necessary for the User. I don't recall exactly why we omitted `name` for the User table - maybe we were thinking about implementing later for oauth? 

Regardless, I think adding it makes sense to me. What do you think?

**Comment by gaelyn** [comment]
I see. Yeah, I think either way it would be good to have a name or username identifier stored for the user.

**Comment by kon-ham** [comment]
Yeah, that totally makes sense to me. I wish I could remember why we didn't include it.

**Comment by kon-ham** [comment]
About to add `name` to our User table through a migration now...

"This makes sense to me." (inside joke for guest readers)

**Comment by kon-ham** [comment]
Please see PR here for actions taken: https://github.com/wdk3/knewharvest_be_api/pull/28

**Comment by kon-ham** [comment]
Closing this issue due to completion.
