### ISSUE TITLE
Create Schema

### ISSUE THREAD

**Issue by lcpulzone** [wdk3/knewharvest_be_api#14]
- [ ] Users - name, farm_name, address
- [ ] Sub_Locations - name, dimensions, micro_climate, user_id

**Comment by lcpulzone** [comment]
- [ ] Users - name, farm_name, address
- [ ] Sub-Locations - name, dimensions, micro_climate, user_id

**Comment by kon-ham** [comment]
Leigh and I got together and designed a schema for this through DB designer. Please see our slack channel for the design image.

**Comment by kon-ham** [comment]
Closing this issue due to completion of ticket.
