### ISSUE TITLE
Create API Endpoint POST - Create new user

### ISSUE THREAD

**Issue by lcpulzone** [wdk3/knewharvest_be_api#17]
Create New User

Request:
```
POST /api/v1/users
Content-Type: application/json
Accept: application/json

body:
{
    "user": "Old McDonald",
    "farm_name": "Old McDonald's Farm",
    "address": "123 ABC St., Bend, OR 12345",
}
```

Response:
```
status: 201
body:
{
  "data": {
    "type": "user",
    "id": null,
    "attributes": {
      "name": "Old McDonald",
      "farm_name": "Old McDonald's Farm",
      "address": "123 ABC St., Charlotte NC 28226"
    }
  }
}
```

**Comment by kon-ham** [comment]
I've created a basic setup that includes a spec test that verifies the route exists for the `POST` user information. We don't have model validations yet so I didn't include any sad paths yet to include into this. However, the route now officially exists once the PR is made through.

**Comment by kon-ham** [comment]
Please see: https://github.com/wdk3/knewharvest_be_api/pull/31 for some work done to progress this issue.
