### ISSUE TITLE
Create Users Controller

### ISSUE THREAD

**Issue by lcpulzone** [wdk3/knewharvest_be_api#8]
- [ ] Create test file for Users controller (/spec/requests/api/v1/users_controller_spec.rb)
- [ ] Create Users controller (/app/controller/api/v1/users_controller.rb)

**Comment by lcpulzone** [comment]
- [ ] Create test file for Users controller (/spec/requests/api/v1/users_controller_spec.rb)
- [ ] Create Users controller (/app/controller/api/v1/users_controller.rb)

**Comment by kon-ham** [comment]
Closing this issue due to completion.
